#!/usr/bin/env bash

# einen hostkey holen: md5 der mac-adresse des lokalen default-gatewaysD
hostkey=$(ip a |grep -A1 $(route -n|grep ^0.0.0.0|cut -c 73-80)|grep ether|cut -d" " -f6|md5sum|cut -b -8)
lb=$(echo $hostkey|cut -b 1-2)
hb=$(echo $hostkey|cut -b 3-4)

ip l set dev "$2" address 02:a5:a7:99:$lb:$hb
ip l set dev "$2" up
modprobe batman-adv
batctl meshif bat-$2 interface create routing_algo BATMAN_IV
batctl meshif bat-$2 interface -M add $2
ip l set dev "bat-$2" up
